server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 909525243788-477pvdr0jef28ekijascml2bpdp5m5ou.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
